# Generated by Django 2.2.1 on 2019-06-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource_param',
            name='dependencies',
        ),
        migrations.AddField(
            model_name='resource',
            name='dependencies',
            field=models.ManyToManyField(related_name='_resource_dependencies_+', to='cluster.Resource'),
        ),
    ]
