# Generated by Django 2.2.4 on 2019-08-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_auto_20190627_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent_param',
            old_name='value',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
