# Generated by Django 2.2.4 on 2019-08-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0003_auto_20190827_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='route',
            new_name='resource_str',
        ),
        migrations.RemoveField(
            model_name='agent_param',
            name='type',
        ),
        migrations.AddField(
            model_name='agent',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='agent',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AddField(
            model_name='agent_param',
            name='content_type',
            field=models.CharField(default='content-type', max_length=50),
        ),
        migrations.AddField(
            model_name='agent_param',
            name='default_value',
            field=models.CharField(default='default', max_length=150),
        ),
        migrations.AddField(
            model_name='agent_param',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='agent_param',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent_param',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
        migrations.AddField(
            model_name='agent_param',
            name='unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agent_param',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
