# Generated by Django 2.2.4 on 2019-08-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0004_auto_20190828_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_param',
            name='default_value',
            field=models.CharField(default='default', max_length=150, null=True),
        ),
    ]
