# Generated by Django 2.2.7 on 2020-01-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0005_auto_20190828_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='dependencies',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='node',
        ),
        migrations.RemoveField(
            model_name='resource_param',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='resource',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='Resource_Param',
        ),
    ]
